version: '3'
services:
  proto:
    command: ./proto/scripts/protoc.sh
    build:
      context: proto
    volumes:
      - .:/proto
  server:
    command: ./scripts/server.sh
    build:
      context: server
    volumes:
      - ./server:/grpc-go-kit
    ports:
      - "50051:50051"
    depends_on:
      - proto
#  envoy:
#    build:
#      context: .
#      dockerfile: DockerfileEnvoy
#    ports:
#      - "8080:8080"
#    links:
#      - server
#  client:
#    command: ./scripts/client.sh
#    build:
#      context: .
#      dockerfile: DockerfileClient
#    volumes:
#      - ./client:/client
#      - /client/node_modules
#    depends_on:
#      - proto
#    ports:
#      - "3000:3000"
#    environment:
#      - EXTEND_ESLINT=true
